version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      -  'MONGODB_USER=user'
      -  'MONGODB_PASS=password!'
    volumes:
      - 'mongodb-data:/data/db'
    networks:
      - mynetwork
    ports:
      - '27017:27017'
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    networks:
      - mynetwork
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      NAME: 'rabbitmq'
  process_xlsx_queue:
    build: .
    ports:
    - '3000:3000'
    volumes:
    - .:/usr/app
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mynetwork

volumes:
  mongodb-data: {}

networks:
  mynetwork:
    driver: bridge
